# stocks.py — NSE Index sector constituents (updated March 2026)

SECTORS = {
    "NIFTY AUTO": [
        "SONACOMS.NS", "UNOMINDA.NS", "BOSCHLTD.NS", "BHARATFORG.NS",
        "BAJAJ-AUTO.NS", "MARUTI.NS", "M&M.NS", "EXIDEIND.NS",
        "TIINDIA.NS", "TVSMOTOR.NS", "HEROMOTOCO.NS", "TATAMOTORS.NS",
        "MOTHERSON.NS", "EICHERMOT.NS", "ASHOKLEY.NS",
    ],

    "NIFTY BANK": [
        "IDFCFIRSTB.NS", "YESBANK.NS", "UNIONBANK.NS", "AUBANK.NS",
        "FEDERALBNK.NS", "CANBK.NS", "INDUSINDBK.NS", "PNB.NS",
        "BANKBARODA.NS", "KOTAKBANK.NS", "SBIN.NS", "HDFCBANK.NS",
        "AXISBANK.NS", "ICICIBANK.NS",
    ],

    "NIFTY FIN SERVICE": [
        "BSE.NS", "RECLTD.NS", "PFC.NS", "SHRIRAMFIN.NS", "SBILIFE.NS",
        "ICICIGI.NS", "SBICARD.NS", "BAJFINANCE.NS", "LICHSGFIN.NS",
        "JIOFIN.NS", "KOTAKBANK.NS", "MUTHOOTFIN.NS", "ICICIPRULI.NS",
        "SBIN.NS", "CHOLAFIN.NS",
    ],

    "NIFTY FMCG": [
        "UBL.NS", "MARICO.NS", "VBL.NS", "NESTLEIND.NS", "PATANJALI.NS",
        "UNITDSPR.NS", "COLPAL.NS", "BRITANNIA.NS", "TATACONSUM.NS",
        "ITC.NS", "RADICO.NS", "GODREJCP.NS", "HINDUNILVR.NS",
        "DABUR.NS", "EMAMILTD.NS",
    ],

    "NIFTY IT": [
        "PERSISTENT.NS", "HCLTECH.NS", "LTM.NS", "WIPRO.NS", "INFY.NS",
        "MPHASIS.NS", "TECHM.NS", "TCS.NS", "COFORGE.NS", "OFSS.NS",
    ],

    "NIFTY MEDIA": [
        "HATHWAY.NS", "NAZARA.NS", "PVRINOX.NS", "SAREGAMA.NS",
        "NETWORK18.NS", "ZEEL.NS", "DBCORP.NS", "PFOCUS.NS",
        "TIPSMUSIC.NS", "SUNTV.NS",
    ],

    "NIFTY METAL": [
        "NMDC.NS", "VEDL.NS", "APLAPOLLO.NS", "HINDALCO.NS",
        "JINDALSTEL.NS", "NATIONALUM.NS", "HINDCOPPER.NS", "TATASTEEL.NS",
        "SAIL.NS", "JSWSTEEL.NS", "HINDZINC.NS", "WELCORP.NS",
        "LLOYDSME.NS", "ADANIENT.NS", "JSL.NS",
    ],

    "NIFTY PHARMA": [
        "BIOCON.NS", "AJANTPHARM.NS", "SUNPHARMA.NS", "DIVISLAB.NS",
        "LUPIN.NS", "IPCALAB.NS", "WOCKPHARMA.NS", "CIPLA.NS",
        "GLENMARK.NS", "AUROPHARMA.NS", "ALKEM.NS", "ZYDUSLIFE.NS",
        "PPLPHARMA.NS", "JBCHEPHARM.NS", "TORNTPHARM.NS", "LAURUSLABS.NS",
    ],

    "NIFTY PSU BANK": [
        "UNIONBANK.NS", "UCOBANK.NS", "PSB.NS", "INDIANB.NS",
        "BANKINDIA.NS", "CANBK.NS", "BANKBARODA.NS", "SBIN.NS",
        "PNB.NS", "IOB.NS", "MAHABANK.NS", "CENTRALBK.NS",
    ],

    "NIFTY REALTY": [
        "OBEROIRLTY.NS", "SOBHA.NS", "BRIGADE.NS", "ANANTRAJ.NS",
        "DLF.NS", "PHOENIXLTD.NS", "LODHA.NS", "PRESTIGE.NS",
        "SIGNATURE.NS", "GODREJPROP.NS",
    ],

    "NIFTY HEALTHCARE": [
        "BIOCON.NS", "SUNPHARMA.NS", "DIVISLAB.NS", "LUPIN.NS",
        "IPCALAB.NS", "CIPLA.NS", "GLENMARK.NS", "AUROPHARMA.NS",
        "PPLPHARMA.NS", "APOLLOHOSP.NS", "DRREDDY.NS", "TORNTPHARM.NS",
        "LAURUSLABS.NS", "ZYDUSLIFE.NS", "ALKEM.NS",
    ],

    "NIFTY CONSUMER DURABLES": [
        "VGUARD.NS", "WHIRLPOOL.NS", "AMBER.NS", "CENTURYPLY.NS",
        "TITAN.NS", "HAVELLS.NS", "CERA.NS", "BATAINDIA.NS",
        "DIXON.NS", "KAJARIACER.NS", "KALYANKJIL.NS", "PGEL.NS",
        "CROMPTON.NS", "VOLTAS.NS", "BLUESTARCO.NS",
    ],

    "NIFTY OIL & GAS": [
        "RELIANCE.NS", "GSPL.NS", "AEGISLOG.NS", "GUJGASLTD.NS",
        "ATGL.NS", "PETRONET.NS", "CASTROLIND.NS", "ONGC.NS",
        "GAIL.NS", "OIL.NS", "IOC.NS", "MGL.NS",
        "HINDPETRO.NS", "BPCL.NS", "IGL.NS",
    ],

    "NIFTY CHEMICALS": [
        "SOLARINDS.NS", "SRF.NS", "NAVINFLUOR.NS", "BAYERCROP.NS",
        "SUMICHEM.NS", "PIDILITIND.NS", "PIIND.NS", "UPL.NS",
        "PCBL.NS", "DEEPAKFERT.NS", "FLUOROCHEM.NS", "LINDEINDIA.NS",
        "SWANCORP.NS", "TATACHEM.NS", "AARTIIND.NS",
    ],
}

# F&O eligible stocks (verified March 2026)
FO_STOCKS = {
    # NIFTY AUTO
    "SONACOMS", "UNOMINDA", "BOSCHLTD", "BHARATFORG", "BAJAJ-AUTO",
    "MARUTI", "M&M", "EXIDEIND", "TIINDIA", "TVSMOTOR", "HEROMOTOCO",
    "TATAMOTORS", "MOTHERSON", "EICHERMOT", "ASHOKLEY",
    # NIFTY BANK
    "IDFCFIRSTB", "YESBANK", "UNIONBANK", "AUBANK", "FEDERALBNK",
    "CANBK", "INDUSINDBK", "PNB", "BANKBARODA", "KOTAKBANK",
    "SBIN", "HDFCBANK", "AXISBANK", "ICICIBANK",
    # NIFTY FIN SERVICE
    "BSE", "RECLTD", "PFC", "SHRIRAMFIN", "SBILIFE", "ICICIGI",
    "SBICARD", "BAJFINANCE", "LICHSGFIN", "JIOFIN", "MUTHOOTFIN",
    "ICICIPRULI", "CHOLAFIN",
    # NIFTY FMCG
    "UBL", "MARICO", "VBL", "NESTLEIND", "PATANJALI", "UNITDSPR",
    "COLPAL", "BRITANNIA", "TATACONSUM", "ITC", "RADICO",
    "GODREJCP", "HINDUNILVR", "DABUR", "EMAMILTD",
    # NIFTY IT
    "PERSISTENT", "HCLTECH", "LTM", "WIPRO", "INFY",
    "MPHASIS", "TECHM", "TCS", "COFORGE", "OFSS",
    # NIFTY MEDIA
    "PVRINOX", "ZEEL", "SUNTV", "NAZARA", "SAREGAMA",
    # NIFTY METAL
    "NMDC", "VEDL", "APLAPOLLO", "HINDALCO", "JINDALSTEL",
    "NATIONALUM", "HINDCOPPER", "TATASTEEL", "SAIL", "JSWSTEEL",
    "HINDZINC", "WELCORP", "LLOYDSME", "ADANIENT", "JSL",
    # NIFTY PHARMA / HEALTHCARE
    "BIOCON", "AJANTPHARM", "SUNPHARMA", "DIVISLAB", "LUPIN",
    "IPCALAB", "WOCKPHARMA", "CIPLA", "GLENMARK", "AUROPHARMA",
    "ALKEM", "ZYDUSLIFE", "PPLPHARMA", "JBCHEPHARM", "TORNTPHARM",
    "LAURUSLABS", "APOLLOHOSP", "DRREDDY",
    # NIFTY PSU BANK
    "UCOBANK", "PSB", "INDIANB", "BANKINDIA", "IOB", "MAHABANK", "CENTRALBK",
    # NIFTY REALTY
    "OBEROIRLTY", "SOBHA", "BRIGADE", "ANANTRAJ", "DLF",
    "PHOENIXLTD", "LODHA", "PRESTIGE", "GODREJPROP",
    # NIFTY CONSUMER DURABLES
    "VGUARD", "WHIRLPOOL", "AMBER", "CENTURYPLY", "TITAN",
    "HAVELLS", "CERA", "BATAINDIA", "DIXON", "KAJARIACER",
    "KALYANKJIL", "PGEL", "CROMPTON", "VOLTAS", "BLUESTARCO",
    # NIFTY OIL & GAS
    "RELIANCE", "GSPL", "AEGISLOG", "GUJGASLTD", "ATGL",
    "PETRONET", "CASTROLIND", "ONGC", "GAIL", "OIL",
    "IOC", "MGL", "HINDPETRO", "BPCL", "IGL",
    # NIFTY CHEMICALS
    "SOLARINDS", "SRF", "NAVINFLUOR", "BAYERCROP", "SUMICHEM",
    "PIDILITIND", "PIIND", "UPL", "PCBL", "DEEPAKFERT",
    "FLUOROCHEM", "LINDEINDIA", "TATACHEM", "AARTIIND",
}

# ---------------------------------------------------------------------------
# Scanner / Boost / RFactor / Planner / F&O Radar stock universe
# Use this list for those features instead of the heatmap SECTORS.
# ---------------------------------------------------------------------------
SCANNER_STOCKS = [
    "360ONE.NS",    "ABB.NS",        "APLAPOLLO.NS",  "AUBANK.NS",
    "ADANIENSOL.NS","ADANIENT.NS",   "ADANIGREEN.NS", "ADANIPORTS.NS",
    "ABCAPITAL.NS", "ALKEM.NS",      "AMBER.NS",      "AMBUJACEM.NS",
    "ANGELONE.NS",  "APOLLOHOSP.NS", "ASHOKLEY.NS",   "ASIANPAINT.NS",
    "ASTRAL.NS",    "AUROPHARMA.NS", "DMART.NS",      "AXISBANK.NS",
    "BSE.NS",       "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS",
    "BAJAJHLDNG.NS","BANDHANBNK.NS", "BANKBARODA.NS", "BANKINDIA.NS",
    "BDL.NS",       "BEL.NS",        "BHARATFORG.NS", "BHEL.NS",
    "BPCL.NS",      "BHARTIARTL.NS", "BIOCON.NS",     "BLUESTARCO.NS",
    "BOSCHLTD.NS",  "BRITANNIA.NS",  "CGPOWER.NS",    "CANBK.NS",
    "CDSL.NS",      "CHOLAFIN.NS",   "CIPLA.NS",      "COALINDIA.NS",
    "COFORGE.NS",   "COLPAL.NS",     "CAMS.NS",       "CONCOR.NS",
    "CROMPTON.NS",  "CUMMINSIND.NS", "DLF.NS",        "DABUR.NS",
    "DALBHARAT.NS", "DELHIVERY.NS",  "DIVISLAB.NS",   "DIXON.NS",
    "DRREDDY.NS",   "ETERNAL.NS",    "EICHERMOT.NS",  "EXIDEIND.NS",
    "NYKAA.NS",     "FORTIS.NS",     "GAIL.NS",       "GMRAIRPORT.NS",
    "GLENMARK.NS",  "GODREJCP.NS",   "GODREJPROP.NS", "GRASIM.NS",
    "HCLTECH.NS",   "HDFCAMC.NS",    "HDFCBANK.NS",   "HDFCLIFE.NS",
    "HAVELLS.NS",   "HEROMOTOCO.NS", "HINDALCO.NS",   "HAL.NS",
    "HINDPETRO.NS", "HINDUNILVR.NS", "HINDZINC.NS",   "POWERINDIA.NS",
    "HUDCO.NS",     "ICICIBANK.NS",  "ICICIGI.NS",    "ICICIPRULI.NS",
    "IDFCFIRSTB.NS","ITC.NS",        "INDIANB.NS",    "IEX.NS",
    "IOC.NS",       "IRFC.NS",       "IREDA.NS",      "INDUSTOWER.NS",
    "INDUSINDBK.NS","NAUKRI.NS",     "INFY.NS",       "INOXWIND.NS",
    "INDIGO.NS",    "JINDALSTEL.NS", "JSWENERGY.NS",  "JSWSTEEL.NS",
    "JIOFIN.NS",    "JUBLFOOD.NS",   "KEI.NS",        "KPITTECH.NS",
    "KALYANKJIL.NS","KAYNES.NS",     "KFINTECH.NS",   "KOTAKBANK.NS",
    "LTF.NS",       "LICHSGFIN.NS",  "LTM.NS",        "LT.NS",
    "LAURUSLABS.NS","LICI.NS",       "LODHA.NS",      "LUPIN.NS",
    "M&M.NS",       "MANAPPURAM.NS", "MANKIND.NS",    "MARICO.NS",
    "MARUTI.NS",    "MFSL.NS",       "MAXHEALTH.NS",  "MAZDOCK.NS",
    "MPHASIS.NS",   "MCX.NS",        "MUTHOOTFIN.NS", "NBCC.NS",
    "NHPC.NS",      "NMDC.NS",       "NTPC.NS",       "NATIONALUM.NS",
    "NESTLEIND.NS", "NUVAMA.NS",     "OBEROIRLTY.NS", "ONGC.NS",
    "OIL.NS",       "PAYTM.NS",      "OFSS.NS",       "POLICYBZR.NS",
    "PGEL.NS",      "PIIND.NS",      "PNBHOUSING.NS", "PAGEIND.NS",
    "PATANJALI.NS", "PERSISTENT.NS", "PETRONET.NS",   "PIDILITIND.NS",
    "PPLPHARMA.NS", "POLYCAB.NS",    "PFC.NS",        "POWERGRID.NS",
    "PREMIERENE.NS","PRESTIGE.NS",   "PNB.NS",        "RBLBANK.NS",
    "RECLTD.NS",    "RVNL.NS",       "RELIANCE.NS",   "SBICARD.NS",
    "SBILIFE.NS",   "SHREECEM.NS",   "SRF.NS",        "SAMMAANCAP.NS",
    "MOTHERSON.NS", "SHRIRAMFIN.NS", "SIEMENS.NS",    "SOLARINDS.NS",
    "SONACOMS.NS",  "SBIN.NS",       "SAIL.NS",       "SUNPHARMA.NS",
    "SUPREMEIND.NS","SUZLON.NS",     "SWIGGY.NS",     "SYNGENE.NS",
    "TATACONSUM.NS","TVSMOTOR.NS",   "TCS.NS",        "TATAELXSI.NS",
    "TATAMOTORS.NS","TATAPOWER.NS",  "TATASTEEL.NS",  "TATATECH.NS",
    "TECHM.NS",     "FEDERALBNK.NS", "INDHOTEL.NS",   "PHOENIXLTD.NS",
    "TITAN.NS",     "TORNTPHARM.NS", "TORNTPOWER.NS", "TRENT.NS",
    "TIINDIA.NS",   "UNOMINDA.NS",   "UPL.NS",        "ULTRACEMCO.NS",
    "UNIONBANK.NS", "UNITDSPR.NS",   "VBL.NS",        "VEDL.NS",
    "IDEA.NS",      "VOLTAS.NS",     "WAAREEENER.NS", "WIPRO.NS",
    "YESBANK.NS",   "ZYDUSLIFE.NS",
]

# All unique symbols flat list (deduplicated) — heatmap sectors only
ALL_SYMBOLS = list({
    sym for symbols in SECTORS.values() for sym in symbols
})
